# syntax=docker/dockerfile:1.7
ARG BASE_IMAGE=ghcr.io/pasturestack/server:v1.6.290
FROM ${BASE_IMAGE}

ARG PASTURESTACK_SERVER_REVISION

LABEL org.opencontainers.image.source="https://github.com/PastureStack/server" \
      org.opencontainers.image.description="PastureStack server compatibility image pinned to the production-accepted Vault Volume Catalog release." \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.version="v1.6.291" \
      org.opencontainers.image.revision="${PASTURESTACK_SERVER_REVISION}" \
      org.opencontainers.image.base.name="ghcr.io/pasturestack/server:v1.6.290"

ENV CATTLE_RANCHER_SERVER_VERSION=v1.6.291
ENV PASTURESTACK_CATALOG_COMMIT=4205e1d3b4fec7691c9e5531375f5268c80924da
ENV DEFAULT_CATTLE_CATALOG_URL='{"catalogs":{"pasturestack":{"url":"https://github.com/PastureStack/catalog-templates.git","branch":"main","pinnedCommit":"4205e1d3b4fec7691c9e5531375f5268c80924da"}}}'
ENV CATTLE_CATALOG_URL='{"catalogs":{"pasturestack":{"url":"https://github.com/PastureStack/catalog-templates.git","branch":"main","pinnedCommit":"4205e1d3b4fec7691c9e5531375f5268c80924da"}}}'

RUN set -eux; \
    bash -n /usr/bin/catalog-service; \
    test -x /usr/local/lib/pasturestack/service-wrapper
