# syntax=docker/dockerfile:1.7
ARG BASE_IMAGE=ghcr.io/pasturestack/server:v1.6.278
FROM ${BASE_IMAGE}

COPY --chmod=0755 bin/entry /usr/bin/entry
COPY --chmod=0755 artifacts/cattle.sh artifacts/performance-env.sh /usr/share/cattle/

ENV PASTURESTACK_SERVER_MODE=externaldb
USER 10001:10001
CMD ["/usr/share/cattle/cattle.sh"]
