# syntax=docker/dockerfile:1.7
ARG BASE_IMAGE=ghcr.io/pasturestack/server:v1.6.280
FROM ${BASE_IMAGE}

ARG PASTURESTACK_SERVER_REVISION

LABEL org.opencontainers.image.source="https://github.com/PastureStack/server" \
      org.opencontainers.image.description="PastureStack server compatibility image with the reviewed Container Schedule Catalog entry." \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.version="v1.6.281" \
      org.opencontainers.image.revision="${PASTURESTACK_SERVER_REVISION}" \
      org.opencontainers.image.base.name="ghcr.io/pasturestack/server:v1.6.280"

ENV CATTLE_RANCHER_SERVER_VERSION=v1.6.281
ENV PASTURESTACK_CATALOG_COMMIT=8e4caa289895855df9706ebf625f401da4ca2e5b
ENV DEFAULT_CATTLE_CATALOG_URL='{"catalogs":{"pasturestack":{"url":"https://github.com/PastureStack/catalog-templates.git","branch":"main","pinnedCommit":"8e4caa289895855df9706ebf625f401da4ca2e5b"}}}'
ENV CATTLE_CATALOG_URL='{"catalogs":{"pasturestack":{"url":"https://github.com/PastureStack/catalog-templates.git","branch":"main","pinnedCommit":"8e4caa289895855df9706ebf625f401da4ca2e5b"}}}'
