# syntax=docker/dockerfile:1.7
ARG BASE_IMAGE=ghcr.io/pasturestack/server:v1.6.286
FROM ${BASE_IMAGE}

ARG PASTURESTACK_SERVER_REVISION

LABEL org.opencontainers.image.source="https://github.com/PastureStack/server" \
      org.opencontainers.image.description="PastureStack server compatibility image pinned to the reviewed Network Diagnostics Catalog release." \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.version="v1.6.287" \
      org.opencontainers.image.revision="${PASTURESTACK_SERVER_REVISION}" \
      org.opencontainers.image.base.name="ghcr.io/pasturestack/server:v1.6.286"

ENV CATTLE_RANCHER_SERVER_VERSION=v1.6.287
ENV PASTURESTACK_CATALOG_COMMIT=18cc041a293a2760fab23e31cc832be1d2084a27
ENV DEFAULT_CATTLE_CATALOG_URL='{"catalogs":{"pasturestack":{"url":"https://github.com/PastureStack/catalog-templates.git","branch":"main","pinnedCommit":"18cc041a293a2760fab23e31cc832be1d2084a27"}}}'
ENV CATTLE_CATALOG_URL='{"catalogs":{"pasturestack":{"url":"https://github.com/PastureStack/catalog-templates.git","branch":"main","pinnedCommit":"18cc041a293a2760fab23e31cc832be1d2084a27"}}}'

RUN set -eux; \
    bash -n /usr/bin/catalog-service; \
    test -x /usr/local/lib/pasturestack/service-wrapper
