#!/bin/bash
set -e -x

apt-get update -q
apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    libyaml-dev \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv \
        tox \
        python3-virtualenv
