#!/bin/bash
set -e

cd "$(dirname "$0")"

TAG=$(<../version)
IMAGE_PREFIX=${IMAGE_PREFIX:-ghcr.io/pasturestack}

mkdir -p ../dist
> ../dist/images

for i in agent server; do
    cd ../$i
    image="${IMAGE_PREFIX}/${i}:${TAG}"
    docker build -t "$image" .
    echo "Created ${image}"
    echo "$image" >> ../dist/images
done
